# Generated by Django 3.2.3 on 2021-06-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210531_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modeldata',
            field=models.TextField(default='{modely:0,modelx:0,modelz:-250,modelScaleX:0.35, modelScaleY:0.35,modelScaleZ:0.35, occluderScaleX:0.6, occluderScaleY:0.7, occluderScaleZ:0.3,  modelRotationX:0,modelRotationY:187,modelRotationZ:0,planez:170,occluderScale:0.5,occluderX:0,occluderY:0,occluderZ:0}', max_length=2000),
        ),
    ]
